import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { routing } from '@/i18n/routing';
import { CV_PDF } from '@/lib/profile/cv-data';
import { countPdfPages } from '../../scripts/pdf-pages.mjs';

describe('CV PDFs (generated by pnpm cv:pdf, committed under public/cv/)', () => {
  for (const locale of routing.locales) {
    it(`${CV_PDF[locale]} exists and fits on two A4 pages at most`, () => {
      const file = path.join(process.cwd(), 'public', CV_PDF[locale]);
      expect(existsSync(file), file).toBe(true);
      const bytes = readFileSync(file);
      expect(bytes.subarray(0, 5).toString('latin1')).toBe('%PDF-');
      const pages = countPdfPages(bytes);
      expect(pages).toBeGreaterThanOrEqual(1);
      expect(pages).toBeLessThanOrEqual(2);
      // A4 media box (595 × 842 pt, within the printer’s precision).
      expect(bytes.toString('latin1')).toMatch(/\/MediaBox\s*\[\s*0\s+0\s+59[45](\.\d+)?\s+84[12](\.\d+)?\s*\]/);
    });
  }

  it('counts pages, not the page tree', () => {
    const fake = Buffer.from('<< /Type /Pages /Count 2 >> << /Type /Page >> << /Type/Page >>', 'latin1');
    expect(countPdfPages(fake)).toBe(2);
  });
});
